apriltag:
  ros__parameters:
    tag_family: "tag36h11"
    
    # [แก้ไข] ต้องมี 3 ค่าให้เท่ากับ tag_ids
    tag_ids: [1, 2]                     
    tag_frames: ["tag_A1", "tag_A2"]
    
    # [แก้ไข] ต้องมี 3 ค่า (หน่วยเป็นเมตร) 
    # ถ้าทุกใบขนาดเท่ากัน (13.5 cm) ก็ใส่ 0.135 สามครั้งครับ
    tag_sizes: [0.135, 0.135]