ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    map_frame: map              # สำหรับอนาคตที่มี AprilTag/SLAM
    odom_frame: odom            # เฟรมหลักของการทำ Fusion
    base_link_frame: base_footprint # ตัวหุ่นยนต์
    world_frame: odom           # ในขั้นตอนนี้ให้ Localize ในเฟรม odom

    # 1. ข้อมูลจาก Encoder (Wheel Odometry)
    odom0: /odom
    odom0_config: [true,  true,  false, # x, y, z
                   false, false, false, # roll, pitch, yaw
                   true,  false, false, # vx, vy, vz
                   false, false, true,  # vroll, vpitch, vyaw (ใช้ Angular Z)
                   false, false, false]
    odom0_relative: false

    # 2. ข้อมูลจาก Realsense (Visual Odometry)
    odom1: /visual_odom
    odom1_config: [true,  true,  false,
                   false, false, false,
                   true,  true,  false, # vx, vy
                   false, false, false,
                   false, false, false]
    odom1_relative: true

    imu0: /imu/data_standard
    imu0_config: [false, false, false, # Position: x, y, z
                  true,  true,  true,  # Orientation: roll, pitch, yaw (ใช้เฉพาะส่วนนี้)
                  false, false, false, # Velocity: vx, vy, vz
                  false, false, false, # Angular Velocity: ปิดไว้เพื่อลดความสับสนของ Filter
                  false, false, false] # Acceleration: ปิดเพราะใน Topic ของคุณเป็น 0.0
    
    imu0_relative: true
    
    # สำคัญ: เปลี่ยนเป็น false เพราะ linear_acceleration ใน topic ของคุณไม่มีข้อมูล (เป็น 0)
    imu0_remove_gravitational_acceleration: false